import type { Exam, Question, ExamResult } from './types'

// ─── Mock Exams ───────────────────────────────────────────────────────────────

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'exam-001',
    title: 'TOEIC Part 5 — Grammar Fundamentals',
    description: 'Covers sentence completion with verb tense, prepositions, and conjunctions. Great for beginners building their grammar base.',
    skill: 'grammar',
    difficulty: 'easy',
    questionCount: 20,
    timeLimitMinutes: 15,
    attempts: 1243,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
    published: true,
  },
  {
    id: 'exam-002',
    title: 'TOEIC Reading Comprehension — Business Emails',
    description: 'Practice reading professional emails, memos, and business correspondence. Focuses on inferencing and detail questions.',
    skill: 'reading',
    difficulty: 'medium',
    questionCount: 25,
    timeLimitMinutes: 30,
    attempts: 987,
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-04-01T12:00:00Z',
    published: true,
  },
  {
    id: 'exam-003',
    title: 'TOEIC Listening — Short Conversations',
    description: 'Focused on Part 3 of the TOEIC Listening section. You will hear two or three people speaking and answer comprehension questions.',
    skill: 'listening',
    difficulty: 'medium',
    questionCount: 20,
    timeLimitMinutes: 20,
    attempts: 756,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-04-10T11:00:00Z',
    published: true,
  },
  {
    id: 'exam-004',
    title: 'Business Vocabulary — Finance & Accounting',
    description: 'Master key vocabulary used in financial reports, banking, and corporate accounting contexts.',
    skill: 'vocabulary',
    difficulty: 'medium',
    questionCount: 30,
    timeLimitMinutes: 20,
    attempts: 1102,
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-04-05T09:00:00Z',
    published: true,
  },
  {
    id: 'exam-005',
    title: 'TOEIC Part 6 — Text Completion (Advanced)',
    description: 'Advanced grammar in context. Fill in the blanks in longer passages — perfect for 800+ score preparation.',
    skill: 'grammar',
    difficulty: 'hard',
    questionCount: 20,
    timeLimitMinutes: 25,
    attempts: 534,
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
    published: true,
  },
  {
    id: 'exam-006',
    title: 'TOEIC Full Reading Section Mock Test',
    description: 'A complete simulation of the TOEIC Reading section with all question types: sentence completion, error identification, and reading comprehension.',
    skill: 'reading',
    difficulty: 'hard',
    questionCount: 40,
    timeLimitMinutes: 75,
    attempts: 421,
    createdAt: '2024-03-10T09:00:00Z',
    updatedAt: '2024-05-15T11:00:00Z',
    published: true,
  },
  {
    id: 'exam-007',
    title: 'Everyday English Vocabulary — Beginner',
    description: 'Common everyday words and phrases used in social and work contexts. Perfect for those just starting out.',
    skill: 'vocabulary',
    difficulty: 'easy',
    questionCount: 20,
    timeLimitMinutes: 15,
    attempts: 2156,
    createdAt: '2024-01-05T08:00:00Z',
    updatedAt: '2024-03-01T09:00:00Z',
    published: true,
  },
  {
    id: 'exam-008',
    title: 'TOEIC Writing — Email Response Practice',
    description: 'Practice writing professional emails in response to prompts. Learn common phrases, correct tone, and proper structure.',
    skill: 'writing',
    difficulty: 'medium',
    questionCount: 10,
    timeLimitMinutes: 20,
    attempts: 389,
    createdAt: '2024-04-01T09:00:00Z',
    updatedAt: '2024-05-10T10:00:00Z',
    published: true,
  },
  {
    id: 'exam-009',
    title: 'TOEIC Listening — Announcements & Talks',
    description: 'Part 4 listening practice: monologues, announcements, and recorded messages from business settings.',
    skill: 'listening',
    difficulty: 'hard',
    questionCount: 20,
    timeLimitMinutes: 25,
    attempts: 612,
    createdAt: '2024-04-05T08:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
    published: true,
  },
  {
    id: 'exam-draft-001',
    title: 'Grammar — Conditionals Deep Dive [DRAFT]',
    description: 'A thorough look at all conditional forms: zero, first, second, third, and mixed conditionals.',
    skill: 'grammar',
    difficulty: 'hard',
    questionCount: 15,
    timeLimitMinutes: 20,
    attempts: 0,
    createdAt: '2024-06-01T08:00:00Z',
    updatedAt: '2024-06-01T08:00:00Z',
    published: false,
  },
]

// ─── Mock Questions for exam-001 ─────────────────────────────────────────────

export const MOCK_QUESTIONS: Record<string, Question[]> = {
  'exam-001': [
    {
      id: 'q-001-01',
      examId: 'exam-001',
      order: 1,
      text: 'The report ______ to the board of directors before the end of the quarter.',
      answers: [
        { id: 'a', text: 'submits' },
        { id: 'b', text: 'will be submitted' },
        { id: 'c', text: 'submitted' },
        { id: 'd', text: 'has submitted' },
      ],
      correctAnswerId: 'b',
      explanation: 'The sentence describes a future obligation using a passive construction. "Will be submitted" is the correct future passive form.',
      skill: 'grammar',
      difficulty: 'easy',
    },
    {
      id: 'q-001-02',
      examId: 'exam-001',
      order: 2,
      text: 'She has been working at the company ______ ten years.',
      answers: [
        { id: 'a', text: 'since' },
        { id: 'b', text: 'for' },
        { id: 'c', text: 'during' },
        { id: 'd', text: 'while' },
      ],
      correctAnswerId: 'b',
      explanation: '"For" is used with periods of time (ten years). "Since" is used with a specific point in time (since 2014).',
      skill: 'grammar',
      difficulty: 'easy',
    },
    {
      id: 'q-001-03',
      examId: 'exam-001',
      order: 3,
      text: 'The new policy requires that all employees ______ their ID badges at all times.',
      answers: [
        { id: 'a', text: 'wear' },
        { id: 'b', text: 'wears' },
        { id: 'c', text: 'wearing' },
        { id: 'd', text: 'wore' },
      ],
      correctAnswerId: 'a',
      explanation: 'After "requires that," the subjunctive mood is used, which takes the base form of the verb (wear) regardless of the subject.',
      skill: 'grammar',
      difficulty: 'medium',
    },
    {
      id: 'q-001-04',
      examId: 'exam-001',
      order: 4,
      text: 'The project was completed ahead of schedule, ______ was a great achievement for the team.',
      answers: [
        { id: 'a', text: 'that' },
        { id: 'b', text: 'which' },
        { id: 'c', text: 'what' },
        { id: 'd', text: 'who' },
      ],
      correctAnswerId: 'b',
      explanation: '"Which" is used in a non-restrictive relative clause referring to the entire previous clause. "That" cannot be used this way.',
      skill: 'grammar',
      difficulty: 'medium',
    },
    {
      id: 'q-001-05',
      examId: 'exam-001',
      order: 5,
      text: 'Neither the manager nor the employees ______ aware of the new regulation.',
      answers: [
        { id: 'a', text: 'was' },
        { id: 'b', text: 'were' },
        { id: 'c', text: 'is' },
        { id: 'd', text: 'are being' },
      ],
      correctAnswerId: 'b',
      explanation: 'With "neither...nor," the verb agrees with the subject closest to it ("employees" — plural), so "were" is correct.',
      skill: 'grammar',
      difficulty: 'hard',
    },
    {
      id: 'q-001-06',
      examId: 'exam-001',
      order: 6,
      text: 'By the time the auditors arrive, the accounting team ______ all the financial documents.',
      answers: [
        { id: 'a', text: 'will review' },
        { id: 'b', text: 'has reviewed' },
        { id: 'c', text: 'will have reviewed' },
        { id: 'd', text: 'reviewed' },
      ],
      correctAnswerId: 'c',
      explanation: '"Will have reviewed" is the future perfect tense, indicating an action that will be completed before another future event ("by the time...arrive").',
      skill: 'grammar',
      difficulty: 'medium',
    },
    {
      id: 'q-001-07',
      examId: 'exam-001',
      order: 7,
      text: 'The company decided to ______ its overseas operations after a thorough market analysis.',
      answers: [
        { id: 'a', text: 'expand' },
        { id: 'b', text: 'expansion' },
        { id: 'c', text: 'expanding' },
        { id: 'd', text: 'expanded' },
      ],
      correctAnswerId: 'a',
      explanation: 'After "to" (infinitive marker), the base form of the verb is required: "to expand."',
      skill: 'grammar',
      difficulty: 'easy',
    },
    {
      id: 'q-001-08',
      examId: 'exam-001',
      order: 8,
      text: 'The announcement ______ until all stakeholders have been notified.',
      answers: [
        { id: 'a', text: 'will delay' },
        { id: 'b', text: 'will be delayed' },
        { id: 'c', text: 'delays' },
        { id: 'd', text: 'is delaying' },
      ],
      correctAnswerId: 'b',
      explanation: 'The announcement is the object of the action (it is being delayed), so the passive voice "will be delayed" is correct.',
      skill: 'grammar',
      difficulty: 'easy',
    },
    {
      id: 'q-001-09',
      examId: 'exam-001',
      order: 9,
      text: 'The training session is ______ for next Tuesday at 9:00 AM.',
      answers: [
        { id: 'a', text: 'scheduled' },
        { id: 'b', text: 'scheduling' },
        { id: 'c', text: 'to schedule' },
        { id: 'd', text: 'schedule' },
      ],
      correctAnswerId: 'a',
      explanation: '"Is scheduled" is a passive construction describing the current state. The training is in a scheduled state.',
      skill: 'grammar',
      difficulty: 'easy',
    },
    {
      id: 'q-001-10',
      examId: 'exam-001',
      order: 10,
      text: 'If the budget ______ approved last month, we could have started the project earlier.',
      answers: [
        { id: 'a', text: 'was' },
        { id: 'b', text: 'were' },
        { id: 'c', text: 'had been' },
        { id: 'd', text: 'has been' },
      ],
      correctAnswerId: 'c',
      explanation: 'This is a third conditional sentence describing an unreal past situation. The if-clause requires the past perfect: "had been approved."',
      skill: 'grammar',
      difficulty: 'hard',
    },
  ],
  'exam-002': [
    {
      id: 'q-002-01',
      examId: 'exam-002',
      order: 1,
      passage: `From: Sarah Mitchell <s.mitchell@globaltech.com>
To: All Staff
Subject: Q3 Performance Review Schedule

Dear Team,

I am writing to inform you that the Q3 performance reviews will take place from September 15 to September 30. All managers are requested to schedule one-on-one meetings with each of their direct reports during this period.

Please ensure that your self-assessment forms are completed and submitted to HR by September 10. These forms are available on the company intranet under the HR section.

If you have any questions about the review process, please contact the HR department directly.

Best regards,
Sarah Mitchell
HR Manager`,
      text: 'What is the main purpose of this email?',
      answers: [
        { id: 'a', text: 'To announce the results of Q3 performance reviews' },
        { id: 'b', text: 'To inform staff about the upcoming performance review schedule' },
        { id: 'c', text: 'To request that managers submit their self-assessment forms' },
        { id: 'd', text: 'To introduce a new HR Manager to the team' },
      ],
      correctAnswerId: 'b',
      explanation: 'The opening line states the purpose clearly: "I am writing to inform you that the Q3 performance reviews will take place..." Option A is incorrect because the results have not been announced. Option C is a detail, not the main purpose.',
      skill: 'reading',
      difficulty: 'easy',
    },
    {
      id: 'q-002-02',
      examId: 'exam-002',
      order: 2,
      passage: `From: Sarah Mitchell <s.mitchell@globaltech.com>
To: All Staff
Subject: Q3 Performance Review Schedule

Dear Team,

I am writing to inform you that the Q3 performance reviews will take place from September 15 to September 30. All managers are requested to schedule one-on-one meetings with each of their direct reports during this period.

Please ensure that your self-assessment forms are completed and submitted to HR by September 10. These forms are available on the company intranet under the HR section.

If you have any questions about the review process, please contact the HR department directly.

Best regards,
Sarah Mitchell
HR Manager`,
      text: 'By what date must employees submit their self-assessment forms?',
      answers: [
        { id: 'a', text: 'September 30' },
        { id: 'b', text: 'September 15' },
        { id: 'c', text: 'September 10' },
        { id: 'd', text: 'The email does not specify' },
      ],
      correctAnswerId: 'c',
      explanation: 'The email explicitly states: "self-assessment forms are completed and submitted to HR by September 10."',
      skill: 'reading',
      difficulty: 'easy',
    },
  ],
}

// ─── Mock Exam Results (history) ─────────────────────────────────────────────

export const MOCK_RESULTS: ExamResult[] = [
  {
    id: 'result-001',
    examId: 'exam-001',
    examTitle: 'TOEIC Part 5 — Grammar Fundamentals',
    examSkill: 'grammar',
    mode: 'practice',
    startedAt: '2024-06-01T09:00:00Z',
    completedAt: '2024-06-01T09:12:00Z',
    durationSeconds: 720,
    score: 80,
    correctCount: 16,
    totalCount: 20,
    passed: true,
    userAnswers: [],
  },
  {
    id: 'result-002',
    examId: 'exam-004',
    examTitle: 'Business Vocabulary — Finance & Accounting',
    examSkill: 'vocabulary',
    mode: 'real-test',
    startedAt: '2024-06-03T14:00:00Z',
    completedAt: '2024-06-03T14:18:00Z',
    durationSeconds: 1080,
    score: 57,
    correctCount: 17,
    totalCount: 30,
    passed: false,
    userAnswers: [],
  },
  {
    id: 'result-003',
    examId: 'exam-002',
    examTitle: 'TOEIC Reading Comprehension — Business Emails',
    examSkill: 'reading',
    mode: 'practice',
    startedAt: '2024-06-05T10:00:00Z',
    completedAt: '2024-06-05T10:27:00Z',
    durationSeconds: 1620,
    score: 92,
    correctCount: 23,
    totalCount: 25,
    passed: true,
    userAnswers: [],
  },
  {
    id: 'result-004',
    examId: 'exam-001',
    examTitle: 'TOEIC Part 5 — Grammar Fundamentals',
    examSkill: 'grammar',
    mode: 'real-test',
    startedAt: '2024-06-08T09:00:00Z',
    completedAt: '2024-06-08T09:14:00Z',
    durationSeconds: 840,
    score: 90,
    correctCount: 18,
    totalCount: 20,
    passed: true,
    userAnswers: [],
  },
  {
    id: 'result-005',
    examId: 'exam-007',
    examTitle: 'Everyday English Vocabulary — Beginner',
    examSkill: 'vocabulary',
    mode: 'practice',
    startedAt: '2024-06-10T15:30:00Z',
    completedAt: '2024-06-10T15:41:00Z',
    durationSeconds: 660,
    score: 75,
    correctCount: 15,
    totalCount: 20,
    passed: true,
    userAnswers: [],
  },
]
